name: doxygen

on: 
  push:
    branches:
      - master

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Compile Docs
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: 'doc/Doxygen'
          enable-latex: true
      - run: ls -lR
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      
